name: unittest

on:
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  test:
    name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [8, 10, 12, 14]
        os: [ubuntu-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}

      - name: get npm cache directory
        id: npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"

      - name: cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ${{ runner.os }}-unittest-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-unittest

      - name: npm ci
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: npm run test
        run: npm run test
